name: "Validates the github yml files"

runs:
  using: "composite"
  steps:
    - name: Install action-validator with asdf
      uses: meza/action-install-action-validator@v1.0.0
    - name: Lint Actions
      run: |
        find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
          | xargs -I {} action-validator --verbose {} && \
        action-validator --verbose action.yml
