name: "A very cool action"
description: "Does the very cool thing in a cool way"

inputs:
  node-version:
    description: "What version to install?"
    type: string
    required: false
    default: latest

outputs:
  npm-version:
    description: "The version of NPM installed"
    value: ${{ steps.something.outputs.npm-version }}

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4.0.4
      id: something
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
