name: "Validates the github yml files"
description: "Runs the action-validator on the relevant yml files"

runs:
  using: "composite"
  steps:
    - name: Install action-validator with asdf
      uses: meza/action-install-action-validator@a5f0179e8a7e7cb831696eff7ea2df2ee6e97f6d # v1.0.5
    - name: Lint Actions
      shell: bash
      run: |
        find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
          | xargs -I {} action-validator --verbose {} && \
        action-validator --verbose action.yml
