name: "Verify PR"

on:
  pull_request:

jobs:
  verify:
    name: Verify PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install action-validator with asdf
        uses: meza/action-install-action-validator@v1.0.0
      - name: Lint Actions
        run: |
          find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
            | xargs -I {} action-validator --verbose {} && \
          action-validator --verbose action.yml
